import type { StaffelConfigV1 } from "../core/types.js";
import { STAFFEL_CLI_VERSION } from "./contracts.js";

export const DEFAULT_STAFFEL_CONFIG: StaffelConfigV1 = Object.freeze({
  configVersion: 1,
  compatibility: {
    workflow: STAFFEL_CLI_VERSION,
    cli: STAFFEL_CLI_VERSION,
    plugin: STAFFEL_CLI_VERSION,
  },
  repository: {
    timezone: "UTC",
    branchPrefix: "work/",
    taskTypes: ["Work"],
    paths: {
      registry: ".staffel/task-registry.md",
      taskPackets: ".staffel/tasks",
      liveLedger: ".staffel/workstreams.md",
      rolePlaybooks: ".staffel/roles",
    },
  },
  workflow: {
    enabledStages: ["ready", "active", "cleanup-pending"],
    stages: {
      ready: {
        kind: "ready",
        nextRole: "implementation",
        rolePlaybook: ".staffel/roles/implementation.md",
        trackerList: "Ready",
        status: "planned",
        beginsAs: "active",
      },
      active: {
        kind: "active",
        nextRole: "implementation",
        rolePlaybook: ".staffel/roles/implementation.md",
        trackerList: "Active",
        status: "in-progress",
        packetStages: ["ready"],
      },
      "cleanup-pending": {
        kind: "lifecycle",
        nextRole: "overseer",
        rolePlaybook: ".staffel/roles/overseer.md",
        trackerList: "Cleanup",
        status: "cleanup-pending",
      },
    },
    normalTransitions: {
      active: ["cleanup-pending"],
    },
    blockedDestinations: {
      closed: "Stage closed is host-owned in the version 1 executable contract.",
    },
  },
  tracker: { provider: "none" },
} satisfies StaffelConfigV1);

export function renderDefaultConfigModule(): string {
  return `// Generated by staffel init. Edit repository policy here.\nexport default ${JSON.stringify(DEFAULT_STAFFEL_CONFIG, null, 2)};\n`;
}
